// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABSKVHQGd-EQj__p7KgRHQ-3uwkQ2A1FQ',
    appId: '1:502187204773:web:dd451d795a7764d9dbed4c',
    messagingSenderId: '502187204773',
    projectId: 'finance-flow-sbb',
    authDomain: 'finance-flow-sbb.firebaseapp.com',
    storageBucket: 'finance-flow-sbb.firebasestorage.app',
    measurementId: 'G-4KNF6ZKKJL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJX83jIThp3XNSwjUetvd9YnqEj_sdeIE',
    appId: '1:502187204773:android:36aef1b5133c2088dbed4c',
    messagingSenderId: '502187204773',
    projectId: 'finance-flow-sbb',
    storageBucket: 'finance-flow-sbb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCP8t8hiUZdoAMD696LWrrpVwbqAoWpknw',
    appId: '1:502187204773:ios:12d0a9e93a839a76dbed4c',
    messagingSenderId: '502187204773',
    projectId: 'finance-flow-sbb',
    storageBucket: 'finance-flow-sbb.firebasestorage.app',
    iosBundleId: 'com.antigravity.financeflow.financeFlow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCP8t8hiUZdoAMD696LWrrpVwbqAoWpknw',
    appId: '1:502187204773:ios:12d0a9e93a839a76dbed4c',
    messagingSenderId: '502187204773',
    projectId: 'finance-flow-sbb',
    storageBucket: 'finance-flow-sbb.firebasestorage.app',
    iosBundleId: 'com.antigravity.financeflow.financeFlow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABSKVHQGd-EQj__p7KgRHQ-3uwkQ2A1FQ',
    appId: '1:502187204773:web:49cad45eeb085723dbed4c',
    messagingSenderId: '502187204773',
    projectId: 'finance-flow-sbb',
    authDomain: 'finance-flow-sbb.firebaseapp.com',
    storageBucket: 'finance-flow-sbb.firebasestorage.app',
    measurementId: 'G-PSV6T72E2H',
  );
}
